#!/usr/bin/env python3
"""Generate comprehensive BCT vocabulary JSON."""
import json, opencc
from pypinyin import Style, pinyin as to_pinyin

cc = opencc.OpenCC('s2t')

def zhuyin(text):
    parts = to_pinyin(text, style=Style.BOPOMOFO)
    return ''.join(p[0] for p in parts)

def trad(text):
    return cc.convert(text)

def w(simp, py, meaning, pos, lv):
    return {
        "simplified": simp, "traditional": trad(simp),
        "pinyin": py, "tone": 0, "zhuyin": zhuyin(simp),
        "meaning_id": meaning, "meaning_en": "",
        "part_of_speech_en": "", "part_of_speech_id": pos,
        "level": lv, "stroke_count": None,
        "example_sentence_zh": "", "example_sentence_pinyin": "",
        "example_sentence_id": "", "example_sentence_en": ""
    }

A = "BCT-A"
B = "BCT-B"

# ─── BCT-A: Basic Business Chinese (~600 words) ───────────────────────────────
BCT_A = [
    # === Greetings & Social ===
    w("你好","nǐ hǎo","halo; hai","Kata Kerja",A),
    w("您好","nín hǎo","halo (hormat)","Kata Kerja",A),
    w("再见","zàijiàn","sampai jumpa","Kata Kerja",A),
    w("谢谢","xièxie","terima kasih","Kata Kerja",A),
    w("不客气","bú kèqi","sama-sama","Kata Kerja",A),
    w("对不起","duìbuqǐ","maaf; minta maaf","Kata Kerja",A),
    w("没关系","méi guānxi","tidak apa-apa","Kata Kerja",A),
    w("请问","qǐngwèn","boleh saya tanya; permisi","Kata Kerja",A),
    w("早上好","zǎoshang hǎo","selamat pagi","Kata Kerja",A),
    w("下午好","xiàwǔ hǎo","selamat siang","Kata Kerja",A),
    w("晚上好","wǎnshang hǎo","selamat malam","Kata Kerja",A),
    w("你好吗","nǐ hǎo ma","apa kabar","Kata Kerja",A),
    w("很好","hěn hǎo","baik-baik saja; sangat baik","Kata Sifat",A),
    w("欢迎","huānyíng","selamat datang","Kata Kerja",A),
    w("幸会","xìnghuì","senang bertemu Anda","Kata Kerja",A),
    # === Identity & Introduction ===
    w("名字","míngzi","nama","Kata Benda",A),
    w("姓","xìng","bermarga; nama keluarga","Kata Kerja",A),
    w("叫","jiào","bernama; memanggil","Kata Kerja",A),
    w("介绍","jièshào","memperkenalkan","Kata Kerja",A),
    w("名片","míngpiàn","kartu nama","Kata Benda",A),
    w("护照","hùzhào","paspor","Kata Benda",A),
    w("签证","qiānzhèng","visa","Kata Benda",A),
    w("国籍","guójí","kewarganegaraan","Kata Benda",A),
    w("年龄","niánlíng","usia; umur","Kata Benda",A),
    w("地址","dìzhǐ","alamat","Kata Benda",A),
    w("电话","diànhuà","telepon","Kata Benda",A),
    w("手机","shǒujī","ponsel; HP","Kata Benda",A),
    w("邮箱","yóuxiāng","kotak surat; email","Kata Benda",A),
    w("电子邮件","diànzǐ yóujiàn","email; surat elektronik","Kata Benda",A),
    w("网站","wǎngzhàn","situs web; website","Kata Benda",A),
    # === Company & Organization ===
    w("公司","gōngsī","perusahaan","Kata Benda",A),
    w("企业","qǐyè","perusahaan; usaha","Kata Benda",A),
    w("工厂","gōngchǎng","pabrik","Kata Benda",A),
    w("商店","shāngdiàn","toko","Kata Benda",A),
    w("银行","yínháng","bank","Kata Benda",A),
    w("医院","yīyuàn","rumah sakit","Kata Benda",A),
    w("学校","xuéxiào","sekolah","Kata Benda",A),
    w("酒店","jiǔdiàn","hotel","Kata Benda",A),
    w("机场","jīchǎng","bandara","Kata Benda",A),
    w("办公室","bàngōngshì","kantor","Kata Benda",A),
    w("总部","zǒngbù","kantor pusat","Kata Benda",A),
    w("分公司","fēn gōngsī","kantor cabang","Kata Benda",A),
    w("部门","bùmén","departemen; bagian","Kata Benda",A),
    w("市场部","shìchǎng bù","departemen pemasaran","Kata Benda",A),
    w("销售部","xiāoshòu bù","departemen penjualan","Kata Benda",A),
    w("财务部","cáiwù bù","departemen keuangan","Kata Benda",A),
    w("人事部","rénshì bù","departemen SDM","Kata Benda",A),
    w("生产部","shēngchǎn bù","departemen produksi","Kata Benda",A),
    w("行政部","xíngzhèng bù","departemen administrasi","Kata Benda",A),
    # === Job Titles ===
    w("经理","jīnglǐ","manajer","Kata Benda",A),
    w("总经理","zǒng jīnglǐ","direktur utama; CEO","Kata Benda",A),
    w("总裁","zǒngcái","presiden direktur","Kata Benda",A),
    w("董事长","dǒngshìzhǎng","ketua dewan direksi","Kata Benda",A),
    w("主任","zhǔrèn","kepala bagian; direktur","Kata Benda",A),
    w("主管","zhǔguǎn","supervisor; atasan","Kata Benda",A),
    w("秘书","mìshū","sekretaris","Kata Benda",A),
    w("助理","zhùlǐ","asisten","Kata Benda",A),
    w("职员","zhíyuán","karyawan; pegawai","Kata Benda",A),
    w("员工","yuángōng","karyawan; staf","Kata Benda",A),
    w("同事","tóngshì","rekan kerja","Kata Benda",A),
    w("上司","shàngsī","atasan; bos","Kata Benda",A),
    w("老板","lǎobǎn","bos; pemilik","Kata Benda",A),
    w("客户","kèhù","klien; pelanggan","Kata Benda",A),
    w("顾客","gùkè","pelanggan; konsumen","Kata Benda",A),
    # === Work & Operations ===
    w("工作","gōngzuò","bekerja; pekerjaan","Kata Kerja",A),
    w("上班","shàngbān","masuk kerja","Kata Kerja",A),
    w("下班","xiàbān","pulang kerja","Kata Kerja",A),
    w("出差","chūchāi","dinas luar; perjalanan bisnis","Kata Kerja",A),
    w("加班","jiābān","lembur","Kata Kerja",A),
    w("请假","qǐngjià","minta izin; mengajukan cuti","Kata Kerja",A),
    w("休息","xiūxi","beristirahat","Kata Kerja",A),
    w("开会","kāihuì","rapat; mengadakan rapat","Kata Kerja",A),
    w("会议","huìyì","rapat; pertemuan","Kata Benda",A),
    w("会议室","huìyìshì","ruang rapat","Kata Benda",A),
    w("报告","bàogào","laporan; melaporkan","Kata Benda",A),
    w("计划","jìhuà","rencana; merencanakan","Kata Benda",A),
    w("安排","ānpái","mengatur; jadwal","Kata Kerja",A),
    w("任务","rènwù","tugas; misi","Kata Benda",A),
    w("项目","xiàngmù","proyek","Kata Benda",A),
    w("负责","fùzé","bertanggung jawab","Kata Kerja",A),
    w("完成","wánchéng","menyelesaikan; selesai","Kata Kerja",A),
    w("提交","tíjiāo","menyerahkan; mengajukan","Kata Kerja",A),
    w("检查","jiǎnchá","memeriksa; inspeksi","Kata Kerja",A),
    w("批准","pīzhǔn","menyetujui; memberikan izin","Kata Kerja",A),
    # === Office Equipment ===
    w("电脑","diànnǎo","komputer","Kata Benda",A),
    w("打印机","dǎyìnjī","printer","Kata Benda",A),
    w("复印机","fùyìnjī","mesin fotokopi","Kata Benda",A),
    w("传真机","chuánzhēnjī","mesin faks","Kata Benda",A),
    w("电话机","diànhuàjī","pesawat telepon","Kata Benda",A),
    w("投影仪","tóuyíngyí","proyektor","Kata Benda",A),
    w("白板","báibǎn","papan tulis putih","Kata Benda",A),
    w("文件","wénjiàn","dokumen; berkas","Kata Benda",A),
    w("合同","hétong","kontrak; perjanjian","Kata Benda",A),
    w("发票","fāpiào","kuitansi; faktur","Kata Benda",A),
    w("表格","biǎogé","formulir; tabel","Kata Benda",A),
    w("信封","xìnfēng","amplop","Kata Benda",A),
    w("笔","bǐ","pena; pensil","Kata Benda",A),
    w("纸","zhǐ","kertas","Kata Benda",A),
    w("文具","wénjù","alat tulis","Kata Benda",A),
    # === Communication ===
    w("打电话","dǎ diànhuà","menelepon","Kata Kerja",A),
    w("接电话","jiē diànhuà","menjawab telepon","Kata Kerja",A),
    w("发短信","fā duǎnxìn","mengirim pesan singkat","Kata Kerja",A),
    w("回复","huífù","membalas; balasan","Kata Kerja",A),
    w("联系","liánxì","menghubungi; kontak","Kata Kerja",A),
    w("通知","tōngzhī","memberitahu; pemberitahuan","Kata Kerja",A),
    w("确认","quèrèn","mengkonfirmasi; memastikan","Kata Kerja",A),
    w("讨论","tǎolùn","mendiskusikan","Kata Kerja",A),
    w("商量","shāngliang","berunding; membicarakan","Kata Kerja",A),
    w("汇报","huìbào","melaporkan kepada atasan","Kata Kerja",A),
    w("说明","shuōmíng","menjelaskan; keterangan","Kata Kerja",A),
    w("询问","xúnwèn","menanyakan; bertanya","Kata Kerja",A),
    # === Numbers & Finance ===
    w("数字","shùzì","angka; nomor","Kata Benda",A),
    w("金额","jīn'é","jumlah uang","Kata Benda",A),
    w("价格","jiàgé","harga","Kata Benda",A),
    w("价钱","jiàqian","harga (informal)","Kata Benda",A),
    w("费用","fèiyòng","biaya; ongkos","Kata Benda",A),
    w("成本","chéngběn","biaya produksi; harga pokok","Kata Benda",A),
    w("利润","lìrùn","keuntungan; laba","Kata Benda",A),
    w("收入","shōurù","pendapatan; penghasilan","Kata Benda",A),
    w("支出","zhīchū","pengeluaran","Kata Benda",A),
    w("预算","yùsuàn","anggaran; budget","Kata Benda",A),
    w("工资","gōngzī","gaji","Kata Benda",A),
    w("奖金","jiǎngjīn","bonus; hadiah uang","Kata Benda",A),
    w("税","shuì","pajak","Kata Benda",A),
    w("付款","fùkuǎn","membayar; pembayaran","Kata Kerja",A),
    w("收款","shōukuǎn","menerima pembayaran","Kata Kerja",A),
    w("转账","zhuǎnzhàng","transfer (uang)","Kata Kerja",A),
    w("现金","xiànjīn","uang tunai","Kata Benda",A),
    w("信用卡","xìnyòngkǎ","kartu kredit","Kata Benda",A),
    w("发票","fāpiào","faktur; kuitansi","Kata Benda",A),
    w("账单","zhàngdān","tagihan; rekening","Kata Benda",A),
    w("账户","zhànghù","rekening; akun","Kata Benda",A),
    w("存款","cúnkuǎn","tabungan; menyimpan uang","Kata Kerja",A),
    w("贷款","dàikuǎn","pinjaman; kredit","Kata Benda",A),
    w("利息","lìxī","bunga (bank)","Kata Benda",A),
    w("汇率","huìlǜ","nilai tukar; kurs","Kata Benda",A),
    # === Products & Trade ===
    w("产品","chǎnpǐn","produk","Kata Benda",A),
    w("商品","shāngpǐn","barang dagangan; komoditi","Kata Benda",A),
    w("货物","huòwù","barang; kargo","Kata Benda",A),
    w("质量","zhìliàng","kualitas; mutu","Kata Benda",A),
    w("数量","shùliàng","kuantitas; jumlah","Kata Benda",A),
    w("型号","xínghào","tipe; model","Kata Benda",A),
    w("规格","guīgé","spesifikasi; ukuran","Kata Benda",A),
    w("样品","yàngpǐn","contoh produk; sampel","Kata Benda",A),
    w("库存","kùcún","stok; persediaan","Kata Benda",A),
    w("订单","dìngdān","pesanan; order","Kata Benda",A),
    w("订购","dìnggòu","memesan; membeli (dalam jumlah)","Kata Kerja",A),
    w("供应","gōngyìng","memasok; pasokan","Kata Kerja",A),
    w("采购","cǎigòu","pengadaan; pembelian","Kata Kerja",A),
    w("进口","jìnkǒu","impor","Kata Kerja",A),
    w("出口","chūkǒu","ekspor","Kata Kerja",A),
    w("交货","jiāohuò","pengiriman barang","Kata Kerja",A),
    w("包装","bāozhuāng","kemasan; mengemas","Kata Benda",A),
    w("运费","yùnfèi","ongkos kirim; biaya pengiriman","Kata Benda",A),
    w("海关","hǎiguān","bea cukai; pabean","Kata Benda",A),
    # === Meetings & Negotiation ===
    w("谈判","tánpàn","negosiasi; berunding","Kata Kerja",A),
    w("谈生意","tán shēngyi","membicarakan bisnis","Kata Kerja",A),
    w("合作","hézuò","kerja sama","Kata Kerja",A),
    w("签合同","qiān hétong","menandatangani kontrak","Kata Kerja",A),
    w("同意","tóngyì","setuju; menyetujui","Kata Kerja",A),
    w("不同意","bù tóngyì","tidak setuju","Kata Kerja",A),
    w("考虑","kǎolǜ","mempertimbangkan","Kata Kerja",A),
    w("决定","juédìng","memutuskan","Kata Kerja",A),
    w("条件","tiáojiàn","syarat; kondisi","Kata Benda",A),
    w("要求","yāoqiú","persyaratan; meminta","Kata Benda",A),
    w("建议","jiànyì","saran; menyarankan","Kata Benda",A),
    w("意见","yìjiàn","pendapat; saran","Kata Benda",A),
    w("问题","wèntí","masalah; pertanyaan","Kata Benda",A),
    w("解决","jiějué","menyelesaikan (masalah)","Kata Kerja",A),
    # === Time & Schedule ===
    w("时间","shíjiān","waktu","Kata Benda",A),
    w("日期","rìqī","tanggal","Kata Benda",A),
    w("今天","jīntiān","hari ini","Kata Benda",A),
    w("明天","míngtiān","besok","Kata Benda",A),
    w("昨天","zuótiān","kemarin","Kata Benda",A),
    w("星期","xīngqī","minggu; hari dalam seminggu","Kata Benda",A),
    w("月份","yuèfèn","bulan (kalender)","Kata Benda",A),
    w("年","nián","tahun","Kata Penghitung",A),
    w("上午","shàngwǔ","pagi (jam kerja)","Kata Benda",A),
    w("下午","xiàwǔ","siang/sore hari","Kata Benda",A),
    w("早上","zǎoshang","pagi hari","Kata Benda",A),
    w("晚上","wǎnshang","malam hari","Kata Benda",A),
    w("现在","xiànzài","sekarang","Kata Benda",A),
    w("以前","yǐqián","dulu; sebelumnya","Kata Benda",A),
    w("以后","yǐhòu","nanti; sesudahnya","Kata Benda",A),
    w("准时","zhǔnshí","tepat waktu","Kata Sifat",A),
    w("迟到","chídào","terlambat","Kata Kerja",A),
    w("约定","yuēdìng","janji; membuat janji","Kata Kerja",A),
    w("预约","yùyuē","membuat janji temu","Kata Kerja",A),
    w("截止日期","jiézhǐ rìqī","batas waktu; deadline","Kata Benda",A),
    # === Travel & Transport ===
    w("飞机","fēijī","pesawat terbang","Kata Benda",A),
    w("火车","huǒchē","kereta api","Kata Benda",A),
    w("地铁","dìtiě","MRT; kereta bawah tanah","Kata Benda",A),
    w("出租车","chūzūchē","taksi","Kata Benda",A),
    w("公共汽车","gōnggòngqìchē","bus umum","Kata Benda",A),
    w("车站","chēzhàn","stasiun; halte","Kata Benda",A),
    w("机场","jīchǎng","bandara; lapangan terbang","Kata Benda",A),
    w("登机","dēngjī","naik pesawat; boarding","Kata Kerja",A),
    w("行李","xíngli","bagasi; koper","Kata Benda",A),
    w("票","piào","tiket; karcis","Kata Benda",A),
    w("预订","yùdìng","memesan; reservasi","Kata Kerja",A),
    w("入住","rùzhù","check-in (hotel)","Kata Kerja",A),
    w("退房","tuìfáng","check-out (hotel)","Kata Kerja",A),
    w("房间","fángjiān","kamar","Kata Benda",A),
    w("单人间","dānrénjiān","kamar single","Kata Benda",A),
    w("双人间","shuāngrénjiān","kamar double","Kata Benda",A),
    # === Dining & Entertainment ===
    w("餐厅","cāntīng","restoran; ruang makan","Kata Benda",A),
    w("菜单","càidān","menu makanan","Kata Benda",A),
    w("点菜","diǎn cài","memesan makanan","Kata Kerja",A),
    w("买单","mǎidān","membayar tagihan restoran","Kata Kerja",A),
    w("请客","qǐngkè","mentraktir; menjamu","Kata Kerja",A),
    w("午餐","wǔcān","makan siang","Kata Benda",A),
    w("晚餐","wǎncān","makan malam","Kata Benda",A),
    w("早餐","zǎocān","sarapan","Kata Benda",A),
    w("饮料","yǐnliào","minuman","Kata Benda",A),
    w("啤酒","píjiǔ","bir","Kata Benda",A),
    w("白酒","báijiǔ","arak putih; spirits Cina","Kata Benda",A),
    w("红酒","hóngjiǔ","anggur merah","Kata Benda",A),
    w("茶","chá","teh","Kata Benda",A),
    w("咖啡","kāfēi","kopi","Kata Benda",A),
    # === Market & Economy ===
    w("市场","shìchǎng","pasar; market","Kata Benda",A),
    w("竞争","jìngzhēng","persaingan; berkompetisi","Kata Kerja",A),
    w("发展","fāzhǎn","berkembang; perkembangan","Kata Kerja",A),
    w("增长","zēngzhǎng","pertumbuhan; meningkat","Kata Kerja",A),
    w("下降","xiàjiàng","menurun; penurunan","Kata Kerja",A),
    w("投资","tóuzī","investasi; berinvestasi","Kata Kerja",A),
    w("经济","jīngjì","ekonomi","Kata Benda",A),
    w("贸易","màoyì","perdagangan","Kata Benda",A),
    w("业务","yèwù","bisnis; operasional","Kata Benda",A),
    w("销售","xiāoshòu","penjualan; menjual","Kata Kerja",A),
    w("营业","yíngyè","berdagang; beroperasi","Kata Kerja",A),
    w("利益","lìyì","keuntungan; manfaat","Kata Benda",A),
    # === Basic Verbs & Adjectives ===
    w("需要","xūyào","membutuhkan; perlu","Kata Kerja",A),
    w("希望","xīwàng","berharap; harapan","Kata Kerja",A),
    w("了解","liǎojiě","memahami; mengerti","Kata Kerja",A),
    w("知道","zhīdào","tahu; mengetahui","Kata Kerja",A),
    w("认为","rènwéi","berpendapat; menganggap","Kata Kerja",A),
    w("表示","biǎoshì","menyatakan; menunjukkan","Kata Kerja",A),
    w("表示","biǎoshì","menyatakan; mengungkapkan","Kata Kerja",A),
    w("提供","tígōng","menyediakan; memberikan","Kata Kerja",A),
    w("使用","shǐyòng","menggunakan; memakai","Kata Kerja",A),
    w("保证","bǎozhèng","menjamin; jaminan","Kata Kerja",A),
    w("准备","zhǔnbèi","mempersiapkan; siap","Kata Kerja",A),
    w("办理","bànlǐ","mengurus; memproses","Kata Kerja",A),
    w("填写","tiánxiě","mengisi (formulir)","Kata Kerja",A),
    w("重要","zhòngyào","penting","Kata Sifat",A),
    w("方便","fāngbiàn","mudah; nyaman; praktis","Kata Sifat",A),
    w("简单","jiǎndān","sederhana; mudah","Kata Sifat",A),
    w("复杂","fùzá","rumit; kompleks","Kata Sifat",A),
    w("正式","zhèngshì","resmi; formal","Kata Sifat",A),
    w("成功","chénggōng","sukses; berhasil","Kata Sifat",A),
    w("满意","mǎnyì","puas; memuaskan","Kata Sifat",A),
    w("顺利","shùnlì","lancar; berjalan baik","Kata Sifat",A),
    w("及时","jíshí","tepat waktu; segera","Kata Sifat",A),
    w("认真","rènzhēn","serius; sungguh-sungguh","Kata Sifat",A),
    w("专业","zhuānyè","profesional; bidang spesialis","Kata Sifat",A),
    # === Locations ===
    w("中国","Zhōngguó","Tiongkok; China","Kata Benda",A),
    w("北京","Běijīng","Beijing","Kata Benda",A),
    w("上海","Shànghǎi","Shanghai","Kata Benda",A),
    w("广州","Guǎngzhōu","Guangzhou","Kata Benda",A),
    w("深圳","Shēnzhèn","Shenzhen","Kata Benda",A),
    w("这里","zhèlǐ","di sini","Kata Benda",A),
    w("那里","nàlǐ","di sana","Kata Benda",A),
    w("附近","fùjìn","di sekitar; dekat sini","Kata Benda",A),
    w("左边","zuǒbian","di sebelah kiri","Kata Benda",A),
    w("右边","yòubian","di sebelah kanan","Kata Benda",A),
    # === Useful Expressions ===
    w("没问题","méi wèntí","tidak masalah; oke","Kata Kerja",A),
    w("可以","kěyǐ","boleh; bisa","Kata Kerja Pembantu",A),
    w("应该","yīnggāi","seharusnya","Kata Kerja Pembantu",A),
    w("必须","bìxū","harus; wajib","Kata Keterangan",A),
    w("不能","bù néng","tidak bisa; tidak boleh","Kata Kerja Pembantu",A),
    w("请","qǐng","silakan; tolong","Kata Kerja",A),
    w("帮助","bāngzhù","membantu; bantuan","Kata Kerja",A),
    w("继续","jìxù","melanjutkan; lanjut","Kata Kerja",A),
    w("开始","kāishǐ","mulai","Kata Kerja",A),
    w("结束","jiéshù","berakhir; selesai","Kata Kerja",A),
    w("马上","mǎshàng","segera; sebentar lagi","Kata Keterangan",A),
    w("尽快","jǐnkuài","sesegera mungkin","Kata Keterangan",A),
    w("最好","zuìhǎo","sebaiknya; yang terbaik","Kata Keterangan",A),
    w("可能","kěnéng","mungkin; kemungkinan","Kata Keterangan",A),
    w("大概","dàgài","kira-kira; sekitar","Kata Keterangan",A),
    w("一共","yígòng","total; seluruhnya","Kata Keterangan",A),
    w("另外","lìngwài","selain itu; di samping itu","Kata Keterangan",A),
    w("所以","suǒyǐ","oleh karena itu","Konjungsi",A),
    w("但是","dànshì","tetapi; namun","Konjungsi",A),
    w("如果","rúguǒ","jika; apabila","Konjungsi",A),
    w("因为","yīnwèi","karena","Konjungsi",A),
]

# ─── BCT-B: Intermediate-Advanced Business Chinese (~300 core words) ──────────
BCT_B = [
    # === Strategy & Management ===
    w("战略","zhànlüè","strategi","Kata Benda",B),
    w("目标","mùbiāo","target; tujuan","Kata Benda",B),
    w("方案","fāng'àn","rencana; solusi","Kata Benda",B),
    w("方针","fāngzhēn","kebijakan; pedoman","Kata Benda",B),
    w("政策","zhèngcè","kebijakan","Kata Benda",B),
    w("执行","zhíxíng","melaksanakan; eksekusi","Kata Kerja",B),
    w("实施","shíshī","mengimplementasikan","Kata Kerja",B),
    w("管理","guǎnlǐ","mengelola; manajemen","Kata Kerja",B),
    w("运营","yùnyíng","operasional; mengelola","Kata Kerja",B),
    w("监督","jiāndū","mengawasi; supervisi","Kata Kerja",B),
    w("协调","xiétiáo","mengoordinasikan","Kata Kerja",B),
    w("推进","tuījìn","mendorong maju; memajukan","Kata Kerja",B),
    w("整合","zhěnghé","mengintegrasikan","Kata Kerja",B),
    w("优化","yōuhuà","mengoptimalkan","Kata Kerja",B),
    w("改进","gǎijìn","memperbaiki; perbaikan","Kata Kerja",B),
    w("评估","pínggū","mengevaluasi; penilaian","Kata Kerja",B),
    w("考核","kǎohé","penilaian kinerja","Kata Kerja",B),
    w("绩效","jìxiào","kinerja; performa","Kata Benda",B),
    w("效率","xiàolǜ","efisiensi","Kata Benda",B),
    w("效益","xiàoyì","manfaat; hasil guna","Kata Benda",B),
    # === Finance & Accounting ===
    w("财务","cáiwù","keuangan","Kata Benda",B),
    w("会计","kuàijì","akuntansi; akuntan","Kata Benda",B),
    w("审计","shěnjì","audit; mengaudit","Kata Kerja",B),
    w("资产","zīchǎn","aset","Kata Benda",B),
    w("负债","fùzhài","utang; kewajiban","Kata Benda",B),
    w("资本","zīběn","modal; kapital","Kata Benda",B),
    w("股权","gǔquán","ekuitas saham","Kata Benda",B),
    w("股票","gǔpiào","saham; surat berharga","Kata Benda",B),
    w("债券","zhàiquàn","obligasi","Kata Benda",B),
    w("融资","róngzī","pembiayaan; pendanaan","Kata Kerja",B),
    w("上市","shàngshì","melantai di bursa; IPO","Kata Kerja",B),
    w("分红","fēnhóng","pembagian dividen","Kata Kerja",B),
    w("现金流","xiànjīn liú","arus kas","Kata Benda",B),
    w("资产负债表","zīchǎn fùzhài biǎo","neraca keuangan","Kata Benda",B),
    w("利润表","lìrùn biǎo","laporan laba rugi","Kata Benda",B),
    w("结算","jiésuàn","penyelesaian transaksi","Kata Kerja",B),
    w("核算","hésuàn","perhitungan biaya","Kata Kerja",B),
    # === Marketing & Sales ===
    w("品牌","pǐnpái","merek; brand","Kata Benda",B),
    w("推广","tuīguǎng","mempromosikan; promosi","Kata Kerja",B),
    w("营销","yíngxiāo","pemasaran; marketing","Kata Kerja",B),
    w("广告","guǎnggào","iklan; reklame","Kata Benda",B),
    w("宣传","xuānchuán","kampanye; propaganda","Kata Kerja",B),
    w("促销","cùxiāo","promosi penjualan","Kata Kerja",B),
    w("渠道","qúdào","saluran distribusi; channel","Kata Benda",B),
    w("分销","fēnxiāo","distribusi; menyalurkan","Kata Kerja",B),
    w("代理","dàilǐ","agen; mewakilkan","Kata Benda",B),
    w("经销商","jīngxiāoshāng","distributor; dealer","Kata Benda",B),
    w("零售","língshòu","eceran; retail","Kata Kerja",B),
    w("批发","pīfā","grosir; wholesale","Kata Kerja",B),
    w("占领市场","zhànlǐng shìchǎng","menguasai pasar","Kata Kerja",B),
    w("市场份额","shìchǎng fèn'é","pangsa pasar","Kata Benda",B),
    w("目标市场","mùbiāo shìchǎng","pasar sasaran","Kata Benda",B),
    w("客户满意度","kèhù mǎnyìdù","kepuasan pelanggan","Kata Benda",B),
    # === HR & Recruitment ===
    w("招聘","zhāopìn","merekrut; lowongan kerja","Kata Kerja",B),
    w("面试","miànshì","wawancara kerja","Kata Kerja",B),
    w("简历","jiǎnlì","CV; daftar riwayat hidup","Kata Benda",B),
    w("培训","péixùn","pelatihan; training","Kata Kerja",B),
    w("晋升","jìnshēng","promosi jabatan","Kata Kerja",B),
    w("离职","lízhí","mengundurkan diri; resign","Kata Kerja",B),
    w("解雇","jiěgù","memecat; PHK","Kata Kerja",B),
    w("合同工","hétong gōng","karyawan kontrak","Kata Benda",B),
    w("正式员工","zhèngshì yuángōng","karyawan tetap","Kata Benda",B),
    w("薪酬","xīnchóu","kompensasi; remunerasi","Kata Benda",B),
    w("福利","fúlì","tunjangan; benefit","Kata Benda",B),
    w("组织架构","zǔzhī jiàgòu","struktur organisasi","Kata Benda",B),
    # === Contracts & Legal ===
    w("协议","xiéyì","perjanjian; kesepakatan","Kata Benda",B),
    w("条款","tiáokuǎn","klausul; ketentuan","Kata Benda",B),
    w("义务","yìwù","kewajiban","Kata Benda",B),
    w("权利","quánlì","hak","Kata Benda",B),
    w("违约","wéiyuē","wanprestasi; melanggar kontrak","Kata Kerja",B),
    w("赔偿","péicháng","kompensasi; ganti rugi","Kata Kerja",B),
    w("纠纷","jiūfēn","sengketa; perselisihan","Kata Benda",B),
    w("仲裁","zhòngcái","arbitrasi","Kata Kerja",B),
    w("诉讼","sùsòng","gugatan; tuntutan hukum","Kata Benda",B),
    w("法律","fǎlǜ","hukum","Kata Benda",B),
    w("法规","fǎguī","peraturan; regulasi","Kata Benda",B),
    w("知识产权","zhīshi chǎnquán","hak kekayaan intelektual","Kata Benda",B),
    w("专利","zhuānlì","paten","Kata Benda",B),
    w("商标","shāngbiāo","merek dagang; trademark","Kata Benda",B),
    w("版权","bǎnquán","hak cipta","Kata Benda",B),
    # === Supply Chain & Logistics ===
    w("供应链","gōngyìng liàn","rantai pasokan; supply chain","Kata Benda",B),
    w("物流","wùliú","logistik","Kata Benda",B),
    w("仓储","cāngchǔ","pergudangan","Kata Benda",B),
    w("配送","pèisòng","pengiriman; distribusi","Kata Kerja",B),
    w("运输","yùnshū","transportasi; pengiriman","Kata Kerja",B),
    w("通关","tōngguān","clearance bea cukai","Kata Kerja",B),
    w("报关","bàoguān","deklarasi pabean","Kata Kerja",B),
    w("交期","jiāoqī","jadwal pengiriman; lead time","Kata Benda",B),
    w("验货","yànhuò","inspeksi barang","Kata Kerja",B),
    w("退货","tuìhuò","retur barang","Kata Kerja",B),
    w("换货","huànhuò","menukar barang","Kata Kerja",B),
    # === Technology & Innovation ===
    w("技术","jìshù","teknologi; teknik","Kata Benda",B),
    w("创新","chuàngxīn","inovasi; berinovasi","Kata Kerja",B),
    w("研发","yánfā","penelitian dan pengembangan; R&D","Kata Kerja",B),
    w("数字化","shùzì huà","digitalisasi","Kata Kerja",B),
    w("互联网","hùliánwǎng","internet","Kata Benda",B),
    w("大数据","dà shùjù","big data","Kata Benda",B),
    w("云计算","yún jìsuàn","komputasi awan; cloud computing","Kata Benda",B),
    w("人工智能","réngōng zhìnéng","kecerdasan buatan; AI","Kata Benda",B),
    w("电子商务","diànzǐ shāngwù","e-commerce; perdagangan elektronik","Kata Benda",B),
    w("平台","píngtái","platform","Kata Benda",B),
    w("系统","xìtǒng","sistem","Kata Benda",B),
    w("软件","ruǎnjiàn","perangkat lunak; software","Kata Benda",B),
    w("硬件","yìngjiàn","perangkat keras; hardware","Kata Benda",B),
    w("数据","shùjù","data","Kata Benda",B),
    w("信息","xìnxī","informasi","Kata Benda",B),
    w("网络","wǎngluò","jaringan; network","Kata Benda",B),
    # === Advanced Communication ===
    w("演讲","yǎnjiǎng","pidato; presentasi","Kata Kerja",B),
    w("汇报","huìbào","melaporkan kepada pimpinan","Kata Kerja",B),
    w("提案","tí'àn","proposal; mengajukan usul","Kata Benda",B),
    w("方案","fāng'àn","solusi; rencana kerja","Kata Benda",B),
    w("总结","zǒngjié","rangkuman; menyimpulkan","Kata Kerja",B),
    w("分析","fēnxī","menganalisis; analisis","Kata Kerja",B),
    w("比较","bǐjiào","membandingkan; perbandingan","Kata Kerja",B),
    w("强调","qiángdiào","menekankan; menonjolkan","Kata Kerja",B),
    w("指出","zhǐchū","menunjukkan; menyebutkan","Kata Kerja",B),
    w("证明","zhèngmíng","membuktikan; bukti","Kata Kerja",B),
    w("解释","jiěshì","menjelaskan; penjelasan","Kata Kerja",B),
    w("补充","bǔchōng","menambahkan; melengkapi","Kata Kerja",B),
    w("反馈","fǎnkuì","umpan balik; feedback","Kata Kerja",B),
    # === International Business ===
    w("外资","wàizī","modal asing; investasi asing","Kata Benda",B),
    w("合资","hézī","usaha patungan; joint venture","Kata Kerja",B),
    w("跨国公司","kuàguó gōngsī","perusahaan multinasional","Kata Benda",B),
    w("对外开放","duìwài kāifàng","keterbukaan terhadap luar","Kata Kerja",B),
    w("自由贸易","zìyóu màoyì","perdagangan bebas","Kata Benda",B),
    w("关税","guānshuì","tarif bea masuk","Kata Benda",B),
    w("外汇","wàihuì","valuta asing; devisa","Kata Benda",B),
    w("美元","Měiyuán","dolar AS","Kata Benda",B),
    w("欧元","Ōuyuán","euro","Kata Benda",B),
    w("人民币","Rénmínbì","renminbi; yuan","Kata Benda",B),
    w("国际","guójì","internasional","Kata Sifat",B),
    w("全球化","quánqiúhuà","globalisasi","Kata Benda",B),
]

# Deduplicate by simplified within BCT_A
seen = set()
bct_a_clean = []
for word in BCT_A:
    key = word['simplified']
    if key not in seen:
        seen.add(key)
        bct_a_clean.append(word)

seen = set()
bct_b_clean = []
for word in BCT_B:
    key = word['simplified']
    if key not in seen:
        seen.add(key)
        bct_b_clean.append(word)

# Save vocab_bct.json
output = {
    "source": "Compiled from official BCT syllabus descriptions and business Chinese resources",
    "note": "BCT-A: ~600-word basic business vocabulary; BCT-B: intermediate-advanced business vocabulary",
    "test": "BCT",
    "levels": {
        "BCT-A": {"official_word_count": 600, "count": len(bct_a_clean), "cefr": "A1-B1"},
        "BCT-B": {"official_word_count": 4000, "count": len(bct_b_clean), "cefr": "B2-C1"}
    },
    "word_count": len(bct_a_clean) + len(bct_b_clean),
    "words": bct_a_clean + bct_b_clean
}

with open('/Users/cunhiung/junxiongmandarinstudio1/data/vocab_bct.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"BCT-A: {len(bct_a_clean)} words")
print(f"BCT-B: {len(bct_b_clean)} words")
print(f"Total BCT: {output['word_count']} words")
