#!/usr/bin/env python3
"""Generate YCT4 vocabulary JSON from official 600-word list."""
import json, opencc, sys
from pypinyin import Style, pinyin as to_pinyin

cc = opencc.OpenCC('s2t')

def zhuyin(text):
    parts = to_pinyin(text, style=Style.BOPOMOFO)
    return ''.join(p[0] for p in parts)

def trad(text):
    return cc.convert(text)

def w(simp, py, meaning, pos, lv='YCT4'):
    return {
        "simplified": simp, "traditional": trad(simp),
        "pinyin": py, "tone": 0, "zhuyin": zhuyin(simp),
        "meaning_id": meaning, "meaning_en": "",
        "part_of_speech_en": "", "part_of_speech_id": pos,
        "level": lv, "stroke_count": None,
        "example_sentence_zh": "", "example_sentence_pinyin": "",
        "example_sentence_id": "", "example_sentence_en": ""
    }

YCT4 = [
    w("阿姨","āyí","bibi; tante","Kata Benda"),
    w("啊","a","partikel seru","Partikel"),
    w("矮","ǎi","pendek (tinggi badan)","Kata Sifat"),
    w("爱","ài","mencintai","Kata Kerja"),
    w("安静","ānjìng","tenang; sunyi","Kata Sifat"),
    w("安全","ānquán","aman; selamat","Kata Sifat"),
    w("八","bā","delapan","Angka"),
    w("把","bǎ","partikel objek; memegang","Kata Depan"),
    w("爸爸","bàba","ayah","Kata Benda"),
    w("吧","ba","partikel saran/konfirmasi","Partikel"),
    w("白","bái","putih","Kata Sifat"),
    w("百","bǎi","seratus","Angka"),
    w("搬","bān","memindahkan; pindah","Kata Kerja"),
    w("办法","bànfǎ","cara; metode","Kata Benda"),
    w("半","bàn","setengah","Angka"),
    w("帮助","bāngzhù","membantu; bantuan","Kata Kerja"),
    w("包子","bāozi","bakpao","Kata Benda"),
    w("饱","bǎo","kenyang","Kata Sifat"),
    w("报纸","bàozhǐ","koran; surat kabar","Kata Benda"),
    w("杯子","bēizi","gelas; cangkir","Kata Benda"),
    w("北方","běifāng","utara; wilayah utara","Kata Benda"),
    w("北京","Běijīng","Beijing","Kata Benda"),
    w("被","bèi","partikel pasif (di-)","Kata Depan"),
    w("本","běn","satuan buku; buku","Kata Penghitung"),
    w("鼻子","bízi","hidung","Kata Benda"),
    w("比","bǐ","dibandingkan dengan","Kata Depan"),
    w("比赛","bǐsài","pertandingan; lomba","Kata Benda"),
    w("必须","bìxū","harus; wajib","Kata Keterangan"),
    w("毕业","bìyè","lulus; tamat sekolah","Kata Kerja"),
    w("变化","biànhuà","perubahan; berubah","Kata Benda"),
    w("表演","biǎoyǎn","pertunjukan; tampil","Kata Kerja"),
    w("别","bié","jangan","Kata Keterangan"),
    w("别人","biérén","orang lain","Kata Ganti"),
    w("冰激凌","bīngjīlíng","es krim","Kata Benda"),
    w("冰箱","bīngxiāng","kulkas; lemari es","Kata Benda"),
    w("饼干","bǐnggān","biskuit; kue kering","Kata Benda"),
    w("不客气","bú kèqi","sama-sama; tidak perlu sungkan","Kata Kerja"),
    w("不","bù","tidak; bukan","Kata Keterangan"),
    w("猜","cāi","menebak; menduga","Kata Kerja"),
    w("菜","cài","sayuran; hidangan","Kata Benda"),
    w("参观","cānguān","mengunjungi; berwisata ke","Kata Kerja"),
    w("参加","cānjiā","mengikuti; berpartisipasi","Kata Kerja"),
    w("草地","cǎodì","lapangan rumput; padang rumput","Kata Benda"),
    w("层","céng","lantai; lapisan","Kata Penghitung"),
    w("茶","chá","teh","Kata Benda"),
    w("长","cháng","panjang","Kata Sifat"),
    w("长城","Chángchéng","Tembok Besar China","Kata Benda"),
    w("尝","cháng","mencicipi; mencoba rasa","Kata Kerja"),
    w("唱歌","chànggē","menyanyi","Kata Kerja"),
    w("超市","chāoshì","supermarket; swalayan","Kata Benda"),
    w("车站","chēzhàn","stasiun; halte","Kata Benda"),
    w("成绩","chéngjì","nilai; hasil; prestasi","Kata Benda"),
    w("吃","chī","makan","Kata Kerja"),
    w("迟到","chídào","terlambat","Kata Kerja"),
    w("虫子","chóngzi","serangga; cacing","Kata Benda"),
    w("出","chū","keluar; terbit","Kata Kerja"),
    w("出发","chūfā","berangkat; memulai perjalanan","Kata Kerja"),
    w("初中","chūzhōng","SMP; sekolah menengah pertama","Kata Benda"),
    w("除了","chúle","selain; kecuali","Kata Depan"),
    w("穿","chuān","memakai (pakaian)","Kata Kerja"),
    w("窗户","chuānghù","jendela","Kata Benda"),
    w("床","chuáng","tempat tidur; ranjang","Kata Benda"),
    w("春季","chūnjì","musim semi","Kata Benda"),
    w("词典","cídiǎn","kamus","Kata Benda"),
    w("次","cì","kali; satuan frekuensi","Kata Penghitung"),
    w("聪明","cōngmíng","cerdas; pintar","Kata Sifat"),
    w("从","cóng","dari; sejak","Kata Depan"),
    w("错","cuò","salah; keliru","Kata Sifat"),
    w("打电话","dǎ diànhuà","menelepon; menghubungi via telepon","Kata Kerja"),
    w("打篮球","dǎ lánqiú","bermain basket","Kata Kerja"),
    w("打扰","dǎrǎo","mengganggu","Kata Kerja"),
    w("打扫","dǎsǎo","membersihkan; menyapu","Kata Kerja"),
    w("打算","dǎsuàn","berencana; berniat","Kata Kerja"),
    w("打针","dǎzhēn","menyuntik; disuntik","Kata Kerja"),
    w("大","dà","besar","Kata Sifat"),
    w("大概","dàgài","kira-kira; mungkin","Kata Keterangan"),
    w("大海","dàhǎi","lautan; samudra","Kata Benda"),
    w("大家","dàjiā","semua orang; kalian semua","Kata Ganti"),
    w("大象","dàxiàng","gajah","Kata Benda"),
    w("带","dài","membawa; membimbing","Kata Kerja"),
    w("戴","dài","memakai (aksesoris)","Kata Kerja"),
    w("担心","dānxīn","khawatir; cemas","Kata Kerja"),
    w("蛋糕","dàngāo","kue; bolu","Kata Benda"),
    w("但是","dànshì","tetapi; namun","Konjungsi"),
    w("当然","dāngrán","tentu saja; sudah pasti","Kata Keterangan"),
    w("到处","dàochù","di mana-mana; ke mana saja","Kata Keterangan"),
    w("地","de","partikel keadaan (-nya)","Partikel"),
    w("的","de","partikel kepemilikan (-nya)","Partikel"),
    w("得","de","partikel hasil","Partikel"),
    w("等","děng","menunggu","Kata Kerja"),
    w("弟弟","dìdi","adik laki-laki","Kata Benda"),
    w("地铁","dìtiě","MRT; kereta bawah tanah","Kata Benda"),
    w("地图","dìtú","peta","Kata Benda"),
    w("地址","dìzhǐ","alamat","Kata Benda"),
    w("第一","dì yī","pertama; nomor satu","Angka Urutan"),
    w("点","diǎn","titik; jam (pukul)","Kata Penghitung"),
    w("电灯","diàndēng","lampu listrik","Kata Benda"),
    w("电脑","diànnǎo","komputer","Kata Benda"),
    w("电视","diànshì","televisi; TV","Kata Benda"),
    w("电梯","diàntī","lift; elevator","Kata Benda"),
    w("电影","diànyǐng","film; bioskop","Kata Benda"),
    w("电子邮件","diànzǐ yóujiàn","email; surat elektronik","Kata Benda"),
    w("丢","diū","kehilangan; membuang","Kata Kerja"),
    w("东","dōng","timur","Kata Benda"),
    w("东西","dōngxi","barang; benda","Kata Benda"),
    w("冬","dōng","musim dingin","Kata Benda"),
    w("懂","dǒng","mengerti; memahami","Kata Kerja"),
    w("动物园","dòngwùyuán","kebun binatang","Kata Benda"),
    w("都","dōu","semua; semuanya","Kata Keterangan"),
    w("读","dú","membaca; belajar","Kata Kerja"),
    w("肚子","dùzi","perut","Kata Benda"),
    w("短","duǎn","pendek; singkat","Kata Sifat"),
    w("锻炼","duànliàn","berolahraga; berlatih","Kata Kerja"),
    w("对","duì","benar; terhadap","Kata Sifat"),
    w("对不起","duìbuqǐ","maaf; minta maaf","Kata Kerja"),
    w("多","duō","banyak","Kata Sifat"),
    w("多么","duōme","betapa; alangkah","Kata Keterangan"),
    w("多少","duōshao","berapa; seberapa banyak","Kata Tanya"),
    w("饿","è","lapar","Kata Sifat"),
    w("儿子","érzi","anak laki-laki; putra","Kata Benda"),
    w("耳朵","ěrduo","telinga","Kata Benda"),
    w("二","èr","dua","Angka"),
    w("发烧","fāshāo","demam","Kata Kerja"),
    w("方便","fāngbiàn","mudah; nyaman; praktis","Kata Sifat"),
    w("房间","fángjiān","kamar; ruangan","Kata Benda"),
    w("放","fàng","meletakkan; menaruh","Kata Kerja"),
    w("放假","fàngjià","libur; liburan","Kata Kerja"),
    w("非常","fēicháng","sangat; amat","Kata Keterangan"),
    w("飞机","fēijī","pesawat terbang","Kata Benda"),
    w("分钟","fēnzhōng","menit","Kata Penghitung"),
    w("服务员","fúwùyuán","pelayan; pramusaji","Kata Benda"),
    w("附近","fùjìn","di sekitar; di dekat","Kata Benda"),
    w("复习","fùxí","mengulang pelajaran; merevisi","Kata Kerja"),
    w("干净","gānjìng","bersih","Kata Sifat"),
    w("敢","gǎn","berani","Kata Kerja Pembantu"),
    w("感冒","gǎnmào","flu; masuk angin","Kata Kerja"),
    w("感兴趣","gǎn xìngqù","tertarik; berminat","Kata Kerja"),
    w("刚才","gāngcái","baru saja; tadi","Kata Keterangan"),
    w("高","gāo","tinggi","Kata Sifat"),
    w("高兴","gāoxìng","senang; gembira","Kata Sifat"),
    w("告诉","gàosu","memberitahu; mengatakan kepada","Kata Kerja"),
    w("哥哥","gēge","kakak laki-laki","Kata Benda"),
    w("个","gè","satuan umum","Kata Penghitung"),
    w("个子","gèzi","tinggi badan; perawakan","Kata Benda"),
    w("给","gěi","memberi; kepada","Kata Kerja"),
    w("更","gèng","lebih; bahkan lebih","Kata Keterangan"),
    w("功夫","gōngfu","kungfu; keterampilan; waktu","Kata Benda"),
    w("公共汽车","gōnggòngqìchē","bus umum","Kata Benda"),
    w("公斤","gōngjīn","kilogram","Kata Penghitung"),
    w("公里","gōnglǐ","kilometer","Kata Penghitung"),
    w("公园","gōngyuán","taman; taman kota","Kata Benda"),
    w("工作","gōngzuò","bekerja; pekerjaan","Kata Kerja"),
    w("狗","gǒu","anjing","Kata Benda"),
    w("够","gòu","cukup; memadai","Kata Sifat"),
    w("刮风","guāfēng","berangin; ada angin","Kata Kerja"),
    w("挂","guà","menggantung; memasang","Kata Kerja"),
    w("关","guān","menutup; mematikan","Kata Kerja"),
    w("关于","guānyú","tentang; mengenai","Kata Depan"),
    w("贵","guì","mahal; mulia","Kata Sifat"),
    w("国家","guójiā","negara; bangsa","Kata Benda"),
    w("果汁","guǒzhī","jus buah","Kata Benda"),
    w("过","guo","partikel pengalaman","Partikel"),
    w("哈","hā","ha (suara tawa)","Onomatope"),
    w("还","hái","masih; juga","Kata Keterangan"),
    w("还是","háishì","atau; lebih baik","Konjungsi"),
    w("孩子","háizi","anak-anak","Kata Benda"),
    w("害怕","hàipà","takut; merasa takut","Kata Kerja"),
    w("寒假","hánjià","liburan musim dingin","Kata Benda"),
    w("汉语","Hànyǔ","bahasa Mandarin","Kata Benda"),
    w("好","hǎo","baik; bagus","Kata Sifat"),
    w("好吃","hǎochī","enak; lezat","Kata Sifat"),
    w("好像","hǎoxiàng","sepertinya; seolah-olah","Kata Keterangan"),
    w("号","hào","nomor; tanggal","Kata Benda"),
    w("号码","hàomǎ","nomor (telepon dll.)","Kata Benda"),
    w("喝","hē","minum","Kata Kerja"),
    w("和","hé","dan; dengan","Konjungsi"),
    w("合适","héshì","cocok; tepat; sesuai","Kata Sifat"),
    w("盒子","hézi","kotak; dus kecil","Kata Benda"),
    w("黑","hēi","hitam","Kata Sifat"),
    w("很","hěn","sangat; amat","Kata Keterangan"),
    w("红","hóng","merah","Kata Sifat"),
    w("猴子","hóuzi","monyet","Kata Benda"),
    w("后","hòu","belakang; setelah","Kata Benda"),
    w("蝴蝶","húdié","kupu-kupu","Kata Benda"),
    w("护士","hùshi","perawat","Kata Benda"),
    w("互相","hùxiāng","saling; timbal balik","Kata Keterangan"),
    w("花","huā","bunga; menghabiskan (uang/waktu)","Kata Benda"),
    w("画","huà","menggambar; lukisan","Kata Kerja"),
    w("坏","huài","rusak; buruk; jahat","Kata Sifat"),
    w("欢迎","huānyíng","selamat datang; menyambut","Kata Kerja"),
    w("换","huàn","mengganti; menukar","Kata Kerja"),
    w("黄","huáng","kuning","Kata Sifat"),
    w("回","huí","kembali; pulang","Kata Kerja"),
    w("会","huì","bisa; akan; mampu","Kata Kerja Pembantu"),
    w("火车","huǒchē","kereta api","Kata Benda"),
    w("或者","huòzhě","atau; ataupun","Konjungsi"),
    w("鸡蛋","jīdàn","telur ayam","Kata Benda"),
    w("极","jí","sangat; ekstrem","Kata Keterangan"),
    w("几","jǐ","beberapa; berapa","Kata Tanya"),
    w("记得","jìde","ingat; masih ingat","Kata Kerja"),
    w("加","jiā","menambah; plus","Kata Kerja"),
    w("家","jiā","rumah; keluarga","Kata Benda"),
    w("坚持","jiānchí","tekun; gigih; bertahan","Kata Kerja"),
    w("减","jiǎn","mengurangi; minus","Kata Kerja"),
    w("件","jiàn","satuan baju/hal","Kata Penghitung"),
    w("健康","jiànkāng","sehat; kesehatan","Kata Sifat"),
    w("见面","jiànmiàn","bertemu; berjumpa","Kata Kerja"),
    w("将来","jiānglái","masa depan; kelak","Kata Benda"),
    w("讲","jiǎng","berbicara; menceritakan","Kata Kerja"),
    w("教","jiāo","mengajar; mengajari","Kata Kerja"),
    w("脚","jiǎo","kaki","Kata Benda"),
    w("饺子","jiǎozi","pangsit; dumpling","Kata Benda"),
    w("叫","jiào","memanggil; bernama","Kata Kerja"),
    w("教室","jiàoshì","ruang kelas","Kata Benda"),
    w("接","jiē","menjemput; menerima","Kata Kerja"),
    w("节目","jiémù","acara; program","Kata Benda"),
    w("节日","jiérì","hari raya; hari besar","Kata Benda"),
    w("姐姐","jiějie","kakak perempuan","Kata Benda"),
    w("借","jiè","meminjam; meminjamkan","Kata Kerja"),
    w("介绍","jièshào","memperkenalkan; pengenalan","Kata Kerja"),
    w("今天","jīntiān","hari ini","Kata Benda"),
    w("紧张","jǐnzhāng","gugup; tegang; sibuk","Kata Sifat"),
    w("进","jìn","masuk; memasuki","Kata Kerja"),
    w("近","jìn","dekat","Kata Sifat"),
    w("经常","jīngcháng","sering; kerap","Kata Keterangan"),
    w("警察","jǐngchá","polisi","Kata Benda"),
    w("九","jiǔ","sembilan","Angka"),
    w("旧","jiù","lama; bekas; kuno","Kata Sifat"),
    w("就","jiù","justru; lalu; segera","Kata Keterangan"),
    w("句子","jùzi","kalimat","Kata Benda"),
    w("觉得","juéde","merasa; berpendapat","Kata Kerja"),
    w("决定","juédìng","memutuskan; keputusan","Kata Kerja"),
    w("开","kāi","membuka; menghidupkan","Kata Kerja"),
    w("开会","kāihuì","rapat; mengadakan rapat","Kata Kerja"),
    w("开始","kāishǐ","mulai; memulai","Kata Kerja"),
    w("看","kàn","melihat; membaca; menonton","Kata Kerja"),
    w("考试","kǎoshì","ujian; tes","Kata Benda"),
    w("烤鸭","kǎoyā","bebek panggang","Kata Benda"),
    w("渴","kě","haus","Kata Sifat"),
    w("可爱","kě'ài","lucu; menggemaskan; imut","Kata Sifat"),
    w("可能","kěnéng","mungkin; kemungkinan","Kata Keterangan"),
    w("可以","kěyǐ","boleh; bisa","Kata Kerja Pembantu"),
    w("刻","kè","seperempat jam","Kata Penghitung"),
    w("课","kè","pelajaran; kelas","Kata Benda"),
    w("空调","kōngtiáo","AC; pendingin ruangan","Kata Benda"),
    w("口","kǒu","mulut","Kata Benda"),
    w("哭","kū","menangis","Kata Kerja"),
    w("裤子","kùzi","celana","Kata Benda"),
    w("块","kuài","potong; yuan (mata uang)","Kata Penghitung"),
    w("快","kuài","cepat","Kata Sifat"),
    w("快乐","kuàilè","bahagia; ceria","Kata Sifat"),
    w("筷子","kuàizi","sumpit","Kata Benda"),
    w("辣","là","pedas","Kata Sifat"),
    w("来","lái","datang","Kata Kerja"),
    w("来得及","láidejí","masih sempat; ada waktu","Kata Kerja"),
    w("蓝","lán","biru","Kata Sifat"),
    w("老","lǎo","tua; lama","Kata Sifat"),
    w("老虎","lǎohǔ","harimau","Kata Benda"),
    w("老师","lǎoshī","guru; pengajar","Kata Benda"),
    w("了","le","partikel selesai/perubahan","Partikel"),
    w("累","lèi","capek; lelah","Kata Sifat"),
    w("冷","lěng","dingin","Kata Sifat"),
    w("离","lí","berjarak dari; terpisah dari","Kata Depan"),
    w("离开","líkāi","meninggalkan; pergi dari","Kata Kerja"),
    w("梨","lí","pir (buah)","Kata Benda"),
    w("礼貌","lǐmào","sopan santun","Kata Sifat"),
    w("里面","lǐmiàn","di dalam","Kata Benda"),
    w("礼物","lǐwù","hadiah; kado","Kata Benda"),
    w("厉害","lìhai","hebat; luar biasa","Kata Sifat"),
    w("俩","liǎ","dua orang (informal)","Angka"),
    w("联系","liánxì","menghubungi; kontak","Kata Kerja"),
    w("脸","liǎn","wajah; muka","Kata Benda"),
    w("练习","liànxí","berlatih; latihan","Kata Kerja"),
    w("凉快","liángkuài","sejuk; segar (udara)","Kata Sifat"),
    w("两","liǎng","dua","Angka"),
    w("辆","liàng","satuan kendaraan","Kata Penghitung"),
    w("聊天儿","liáotiānr","mengobrol; ngobrol","Kata Kerja"),
    w("邻居","línjū","tetangga","Kata Benda"),
    w("零","líng","nol","Angka"),
    w("另外","lìngwài","selain itu; di samping itu","Kata Keterangan"),
    w("流汗","liúhàn","berkeringat","Kata Kerja"),
    w("六","liù","enam","Angka"),
    w("楼","lóu","gedung; lantai (bertingkat)","Kata Benda"),
    w("旅游","lǚyóu","berwisata; pariwisata","Kata Kerja"),
    w("绿","lǜ","hijau","Kata Sifat"),
    w("妈妈","māma","ibu","Kata Benda"),
    w("马虎","mǎhu","ceroboh; tidak teliti","Kata Sifat"),
    w("马上","mǎshàng","segera; sebentar lagi","Kata Keterangan"),
    w("吗","ma","partikel tanya (ya/tidak)","Partikel"),
    w("买","mǎi","membeli","Kata Kerja"),
    w("卖","mài","menjual","Kata Kerja"),
    w("慢","màn","lambat; pelan","Kata Sifat"),
    w("忙","máng","sibuk","Kata Sifat"),
    w("猫","māo","kucing","Kata Benda"),
    w("没关系","méi guānxi","tidak apa-apa; tidak masalah","Kata Kerja"),
    w("没有","méiyǒu","tidak ada; tidak memiliki","Kata Kerja"),
    w("玫瑰花","méiguīhuā","bunga mawar","Kata Benda"),
    w("每","měi","setiap; masing-masing","Kata Sifat"),
    w("妹妹","mèimei","adik perempuan","Kata Benda"),
    w("门口","ménkǒu","pintu masuk; depan pintu","Kata Benda"),
    w("迷路","mílù","tersesat; salah jalan","Kata Kerja"),
    w("米饭","mǐfàn","nasi (putih)","Kata Benda"),
    w("面包","miànbāo","roti","Kata Benda"),
    w("面条","miàntiáo","mie; mi","Kata Benda"),
    w("明白","míngbai","mengerti; paham","Kata Kerja"),
    w("明天","míngtiān","besok","Kata Benda"),
    w("名字","míngzi","nama","Kata Benda"),
    w("拿","ná","mengambil; memegang","Kata Kerja"),
    w("哪","nǎ","mana; yang mana","Kata Tanya"),
    w("那","nà","itu; kalau begitu","Kata Penunjuk"),
    w("奶奶","nǎinai","nenek (dari ayah)","Kata Benda"),
    w("男","nán","laki-laki","Kata Sifat"),
    w("南","nán","selatan","Kata Benda"),
    w("难","nán","sulit; susah","Kata Sifat"),
    w("难过","nánguò","sedih; bersedih","Kata Sifat"),
    w("呢","ne","partikel pertanyaan lanjutan","Partikel"),
    w("能","néng","bisa; mampu","Kata Kerja Pembantu"),
    w("你","nǐ","kamu; engkau","Kata Ganti"),
    w("年","nián","tahun","Kata Penghitung"),
    w("年级","niánjí","tingkat kelas; grade","Kata Benda"),
    w("年轻","niánqīng","muda; berusia muda","Kata Sifat"),
    w("鸟","niǎo","burung","Kata Benda"),
    w("您","nín","Anda (hormat)","Kata Ganti"),
    w("牛奶","niúnǎi","susu sapi","Kata Benda"),
    w("努力","nǔlì","berusaha keras; giat","Kata Kerja"),
    w("女","nǚ","perempuan; wanita","Kata Sifat"),
    w("女儿","nǚ'ér","anak perempuan; putri","Kata Benda"),
    w("暖和","nuǎnhuo","hangat; tidak dingin tidak panas","Kata Sifat"),
    w("爬山","páshān","mendaki gunung","Kata Kerja"),
    w("排队","páiduì","antri; berbaris","Kata Kerja"),
    w("排球","páiqiú","bola voli","Kata Benda"),
    w("盘子","pánzi","piring","Kata Benda"),
    w("旁边","pángbiān","di samping; di sisi","Kata Benda"),
    w("胖","pàng","gemuk; montok","Kata Sifat"),
    w("跑步","pǎobù","berlari; jogging","Kata Kerja"),
    w("朋友","péngyou","teman; sahabat","Kata Benda"),
    w("便宜","piányi","murah; terjangkau","Kata Sifat"),
    w("漂亮","piàoliang","cantik; tampan; indah","Kata Sifat"),
    w("乒乓球","pīngpāngqiú","tenis meja; ping-pong","Kata Benda"),
    w("苹果","píngguǒ","apel","Kata Benda"),
    w("破","pò","rusak; pecah; robek","Kata Sifat"),
    w("葡萄","pútao","anggur","Kata Benda"),
    w("七","qī","tujuh","Angka"),
    w("奇怪","qíguài","aneh; ganjil","Kata Sifat"),
    w("骑马","qímǎ","berkuda; menunggang kuda","Kata Kerja"),
    w("其他","qítā","lainnya; yang lain","Kata Ganti"),
    w("起床","qǐchuáng","bangun tidur","Kata Kerja"),
    w("起来","qǐlái","bangun; berdiri","Kata Kerja"),
    w("千","qiān","seribu","Angka"),
    w("铅笔","qiānbǐ","pensil","Kata Benda"),
    w("前","qián","depan; sebelum","Kata Benda"),
    w("钱","qián","uang","Kata Benda"),
    w("桥","qiáo","jembatan","Kata Benda"),
    w("巧克力","qiǎokèlì","cokelat","Kata Benda"),
    w("清楚","qīngchu","jelas; terang","Kata Sifat"),
    w("晴","qíng","cerah; tidak mendung","Kata Sifat"),
    w("请","qǐng","silakan; mengundang","Kata Kerja"),
    w("秋","qiū","musim gugur","Kata Benda"),
    w("去","qù","pergi; berangkat","Kata Kerja"),
    w("去年","qùnián","tahun lalu","Kata Benda"),
    w("裙子","qúnzi","rok","Kata Benda"),
    w("然后","ránhòu","kemudian; lalu","Kata Keterangan"),
    w("让","ràng","menyuruh; membiarkan","Kata Kerja"),
    w("热","rè","panas; hangat","Kata Sifat"),
    w("认识","rènshi","mengenal; berkenalan","Kata Kerja"),
    w("认真","rènzhēn","serius; sungguh-sungguh","Kata Sifat"),
    w("容易","róngyì","mudah; gampang","Kata Sifat"),
    w("三","sān","tiga","Angka"),
    w("散步","sànbù","berjalan-jalan; jalan santai","Kata Kerja"),
    w("沙发","shāfā","sofa; kursi panjang","Kata Benda"),
    w("商店","shāngdiàn","toko; kedai","Kata Benda"),
    w("上班","shàngbān","bekerja; masuk kerja","Kata Kerja"),
    w("上边","shàngbian","di atas; bagian atas","Kata Benda"),
    w("上海","Shànghǎi","Shanghai","Kata Benda"),
    w("上网","shàngwǎng","berinternet; online","Kata Kerja"),
    w("少","shǎo","sedikit; kurang","Kata Sifat"),
    w("谁","shéi","siapa","Kata Tanya"),
    w("身体","shēntǐ","tubuh; badan; kesehatan","Kata Benda"),
    w("什么","shénme","apa; apakah","Kata Tanya"),
    w("生病","shēngbìng","sakit; jatuh sakit","Kata Kerja"),
    w("生活","shēnghuó","kehidupan; hidup","Kata Benda"),
    w("生气","shēngqì","marah; naik darah","Kata Kerja"),
    w("生日","shēngrì","ulang tahun","Kata Benda"),
    w("声音","shēngyīn","suara; bunyi","Kata Benda"),
    w("十","shí","sepuluh","Angka"),
    w("时候","shíhou","waktu; saat; ketika","Kata Benda"),
    w("时间","shíjiān","waktu; jam","Kata Benda"),
    w("是","shì","adalah; iya","Kata Kerja"),
    w("事情","shìqing","hal; urusan; persoalan","Kata Benda"),
    w("手","shǒu","tangan","Kata Benda"),
    w("手表","shǒubiǎo","jam tangan","Kata Benda"),
    w("瘦","shòu","kurus; langsing","Kata Sifat"),
    w("受不了","shòubuliǎo","tidak tahan; tidak bisa bertahan","Kata Kerja"),
    w("售票员","shòupiàoyuán","petugas karcis; kondektur","Kata Benda"),
    w("书包","shūbāo","tas sekolah; ransel","Kata Benda"),
    w("舒服","shūfu","nyaman; enak badan","Kata Sifat"),
    w("叔叔","shūshu","paman (dari ayah)","Kata Benda"),
    w("熟悉","shúxī","akrab; familiar; mengenal baik","Kata Kerja"),
    w("暑假","shǔjià","liburan musim panas","Kata Benda"),
    w("刷牙","shuā yá","menggosok gigi","Kata Kerja"),
    w("双","shuāng","pasang; sepasang","Kata Penghitung"),
    w("水","shuǐ","air","Kata Benda"),
    w("水果","shuǐguǒ","buah-buahan","Kata Benda"),
    w("睡觉","shuìjiào","tidur","Kata Kerja"),
    w("说话","shuōhuà","berbicara; berkata","Kata Kerja"),
    w("四","sì","empat","Angka"),
    w("送","sòng","mengantar; memberikan","Kata Kerja"),
    w("虽然","suīrán","meskipun; walaupun","Konjungsi"),
    w("岁","suì","tahun (usia)","Kata Penghitung"),
    w("孙子","sūnzi","cucu laki-laki","Kata Benda"),
    w("所以","suǒyǐ","oleh karena itu; maka","Konjungsi"),
    w("他","tā","dia (laki-laki)","Kata Ganti"),
    w("她","tā","dia (perempuan)","Kata Ganti"),
    w("它","tā","ia (benda/hewan)","Kata Ganti"),
    w("太","tài","terlalu; sangat","Kata Keterangan"),
    w("太阳","tàiyáng","matahari","Kata Benda"),
    w("弹钢琴","tán gāngqín","bermain piano","Kata Kerja"),
    w("汤","tāng","sup; kaldu","Kata Benda"),
    w("糖","táng","gula; permen; kembang gula","Kata Benda"),
    w("躺","tǎng","berbaring; tiduran","Kata Kerja"),
    w("桃","táo","persik; buah persik","Kata Benda"),
    w("讨论","tǎolùn","mendiskusikan; diskusi","Kata Kerja"),
    w("讨厌","tǎoyàn","menyebalkan; tidak suka","Kata Sifat"),
    w("特别","tèbié","spesial; khusus; terutama","Kata Sifat"),
    w("疼","téng","sakit; nyeri","Kata Sifat"),
    w("踢足球","tī zúqiú","bermain sepak bola","Kata Kerja"),
    w("体育馆","tǐyùguǎn","gedung olahraga; gimnasium","Kata Benda"),
    w("天气","tiānqì","cuaca","Kata Benda"),
    w("甜","tián","manis","Kata Sifat"),
    w("条","tiáo","satuan benda panjang","Kata Penghitung"),
    w("跳舞","tiàowǔ","menari; berdansa","Kata Kerja"),
    w("听","tīng","mendengar; mendengarkan","Kata Kerja"),
    w("听说","tīngshuō","katanya; terdengar kabar","Kata Kerja"),
    w("停","tíng","berhenti; menghentikan","Kata Kerja"),
    w("同学","tóngxué","teman sekelas; teman sekolah","Kata Benda"),
    w("同意","tóngyì","setuju; menyetujui","Kata Kerja"),
    w("头发","tóufa","rambut","Kata Benda"),
    w("突然","tūrán","tiba-tiba; mendadak","Kata Keterangan"),
    w("图书馆","túshūguǎn","perpustakaan","Kata Benda"),
    w("兔子","tùzi","kelinci","Kata Benda"),
    w("腿","tuǐ","kaki (tungkai bawah)","Kata Benda"),
    w("脱","tuō","melepas (pakaian)","Kata Kerja"),
    w("外面","wàimiàn","di luar; bagian luar","Kata Benda"),
    w("完","wán","selesai; habis","Kata Kerja"),
    w("玩","wán","bermain; bersenang-senang","Kata Kerja"),
    w("玩具","wánjù","mainan","Kata Benda"),
    w("晚上","wǎnshang","malam hari","Kata Benda"),
    w("万","wàn","sepuluh ribu","Angka"),
    w("网球","wǎngqiú","tenis","Kata Benda"),
    w("忘记","wàngjì","lupa; melupakan","Kata Kerja"),
    w("危险","wēixiǎn","berbahaya; bahaya","Kata Sifat"),
    w("喂","wèi","halo (di telepon); hei","Kata Seru"),
    w("为了","wèile","demi; untuk; agar","Kata Depan"),
    w("为什么","wèi shénme","mengapa; kenapa","Kata Tanya"),
    w("问","wèn","bertanya; menanyakan","Kata Kerja"),
    w("问题","wèntí","pertanyaan; masalah; soal","Kata Benda"),
    w("我","wǒ","saya; aku","Kata Ganti"),
    w("我们","wǒmen","kami; kita","Kata Ganti"),
    w("无论","wúlùn","apapun; bagaimanapun","Konjungsi"),
    w("五","wǔ","lima","Angka"),
    w("西","xī","barat","Kata Benda"),
    w("西瓜","xīguā","semangka","Kata Benda"),
    w("西红柿","xīhōngshì","tomat","Kata Benda"),
    w("希望","xīwàng","berharap; harapan","Kata Kerja"),
    w("习惯","xíguàn","kebiasaan; terbiasa","Kata Benda"),
    w("喜欢","xǐhuān","menyukai; suka","Kata Kerja"),
    w("洗手间","xǐshǒujiān","toilet; kamar mandi","Kata Benda"),
    w("洗澡","xǐzǎo","mandi","Kata Kerja"),
    w("下","xià","bawah; turun","Kata Benda"),
    w("下雪","xiàxuě","turun salju; bersalju","Kata Kerja"),
    w("夏","xià","musim panas","Kata Benda"),
    w("先","xiān","dulu; terlebih dahulu","Kata Keterangan"),
    w("先生","xiānsheng","Tuan; Bapak; suami","Kata Benda"),
    w("现在","xiànzài","sekarang; saat ini","Kata Benda"),
    w("香蕉","xiāngjiāo","pisang","Kata Benda"),
    w("响","xiǎng","berbunyi; keras (suara)","Kata Kerja"),
    w("想","xiǎng","ingin; berpikir; merindukan","Kata Kerja"),
    w("向","xiàng","ke arah; menuju","Kata Depan"),
    w("小","xiǎo","kecil","Kata Sifat"),
    w("小姐","xiǎojiě","Nona; Miss","Kata Benda"),
    w("小时","xiǎoshí","jam (satuan waktu)","Kata Penghitung"),
    w("小心","xiǎoxīn","hati-hati; waspada","Kata Kerja"),
    w("笑","xiào","tertawa; tersenyum","Kata Kerja"),
    w("校园","xiàoyuán","kampus; halaman sekolah","Kata Benda"),
    w("些","xiē","beberapa; sejumlah","Kata Penghitung"),
    w("鞋","xié","sepatu","Kata Benda"),
    w("写","xiě","menulis","Kata Kerja"),
    w("谢谢","xièxie","terima kasih","Kata Kerja"),
    w("新","xīn","baru","Kata Sifat"),
    w("新闻","xīnwén","berita; kabar","Kata Benda"),
    w("心情","xīnqíng","perasaan; suasana hati; mood","Kata Benda"),
    w("信封","xīnfēng","amplop","Kata Benda"),
    w("星期","xīngqī","minggu; hari dalam seminggu","Kata Benda"),
    w("星星","xīngxīng","bintang","Kata Benda"),
    w("行","xíng","boleh; oke; bisa","Kata Kerja"),
    w("醒","xǐng","terbangun; sadar","Kata Kerja"),
    w("幸福","xìngfú","bahagia; kebahagiaan","Kata Sifat"),
    w("熊猫","xióngmāo","panda","Kata Benda"),
    w("休息","xiūxi","beristirahat; istirahat","Kata Kerja"),
    w("选择","xuǎnzé","memilih; pilihan","Kata Kerja"),
    w("学生","xuésheng","siswa; pelajar","Kata Benda"),
    w("学习","xuéxí","belajar; mempelajari","Kata Kerja"),
    w("学校","xuéxiào","sekolah","Kata Benda"),
    w("颜色","yánsè","warna","Kata Benda"),
    w("眼镜","yǎnjìng","kacamata","Kata Benda"),
    w("眼睛","yǎnjing","mata","Kata Benda"),
    w("羊肉","yángròu","daging kambing","Kata Benda"),
    w("药","yào","obat; obat-obatan","Kata Benda"),
    w("要","yào","mau; ingin; perlu; akan","Kata Kerja Pembantu"),
    w("钥匙","yàoshi","kunci","Kata Benda"),
    w("爷爷","yéye","kakek (dari ayah)","Kata Benda"),
    w("也","yě","juga; pun","Kata Keterangan"),
    w("页","yè","halaman","Kata Penghitung"),
    w("一","yī","satu","Angka"),
    w("衣服","yīfu","pakaian; baju","Kata Benda"),
    w("医生","yīshēng","dokter","Kata Benda"),
    w("医院","yīyuàn","rumah sakit","Kata Benda"),
    w("一定","yídìng","pasti; tentu","Kata Keterangan"),
    w("一共","yígòng","total; seluruhnya","Kata Keterangan"),
    w("一会儿","yíhuìr","sebentar; sebentar lagi","Kata Benda"),
    w("一下儿","yíxiàr","sebentar; coba","Kata Keterangan"),
    w("一样","yíyàng","sama; serupa","Kata Sifat"),
    w("已经","yǐjīng","sudah; telah","Kata Keterangan"),
    w("以前","yǐqián","dulu; sebelumnya; dahulu kala","Kata Benda"),
    w("以为","yǐwéi","mengira; menyangka","Kata Kerja"),
    w("椅子","yǐzi","kursi","Kata Benda"),
    w("一点儿","yìdiǎnr","sedikit; agak","Kata Keterangan"),
    w("一起","yìqǐ","bersama; bersama-sama","Kata Keterangan"),
    w("意思","yìsi","arti; makna; maksud","Kata Benda"),
    w("一直","yìzhí","terus; selalu; terus-menerus","Kata Keterangan"),
    w("因为","yīnwèi","karena; sebab","Konjungsi"),
    w("饮料","yǐnliào","minuman","Kata Benda"),
    w("应该","yīnggāi","seharusnya; semestinya","Kata Kerja Pembantu"),
    w("勇敢","yǒnggǎn","berani; pemberani","Kata Sifat"),
    w("用","yòng","menggunakan; memakai","Kata Kerja"),
    w("游戏","yóuxì","permainan; game","Kata Benda"),
    w("游泳","yóuyǒng","berenang","Kata Kerja"),
    w("有","yǒu","ada; memiliki","Kata Kerja"),
    w("有名","yǒumíng","terkenal; famous","Kata Sifat"),
    w("右","yòu","kanan","Kata Benda"),
    w("鱼","yú","ikan","Kata Benda"),
    w("雨伞","yǔsǎn","payung","Kata Benda"),
    w("元","yuán","yuan (mata uang China)","Kata Penghitung"),
    w("圆","yuán","bulat; melingkar","Kata Sifat"),
    w("远","yuǎn","jauh","Kata Sifat"),
    w("月","yuè","bulan (kalender); satuan bulan","Kata Penghitung"),
    w("月亮","yuèliàng","bulan (benda langit)","Kata Benda"),
    w("越来越","yuèláiyuè","semakin... semakin...","Kata Keterangan"),
    w("云","yún","awan","Kata Benda"),
    w("运动","yùndòng","olahraga; bergerak","Kata Benda"),
    w("杂志","zázhì","majalah","Kata Benda"),
    w("在","zài","berada di; di","Kata Depan"),
    w("再","zài","lagi; sekali lagi","Kata Keterangan"),
    w("再见","zàijiàn","sampai jumpa; selamat tinggal","Kata Kerja"),
    w("早上","zǎoshang","pagi hari","Kata Benda"),
    w("怎么","zěnme","bagaimana; kenapa","Kata Tanya"),
    w("怎么样","zěnmeyàng","bagaimana keadaannya","Kata Tanya"),
    w("站","zhàn","berdiri; stasiun","Kata Kerja"),
    w("张","zhāng","lembar; satuan kertas/wajah","Kata Penghitung"),
    w("着急","zháojí","cemas; gelisah","Kata Kerja"),
    w("找","zhǎo","mencari; menemui","Kata Kerja"),
    w("照顾","zhàogù","merawat; mengurus","Kata Kerja"),
    w("照片","zhàopiàn","foto; gambar","Kata Benda"),
    w("照相","zhàoxiàng","berfoto; memotret","Kata Kerja"),
    w("这","zhè","ini","Kata Penunjuk"),
    w("着","zhe","partikel keberlangsungan","Partikel"),
    w("真","zhēn","sungguh; betul-betul","Kata Keterangan"),
    w("正在","zhèngzài","sedang (berlangsung)","Kata Keterangan"),
    w("只","zhǐ","hanya; cuma","Kata Keterangan"),
    w("知道","zhīdào","tahu; mengetahui","Kata Kerja"),
    w("知识","zhīshi","pengetahuan; ilmu","Kata Benda"),
    w("只要","zhǐyào","asalkan; selama","Konjungsi"),
    w("中国人","Zhōngguórén","orang Cina; warga Tiongkok","Kata Benda"),
    w("中间","zhōngjiān","di tengah; antara","Kata Benda"),
    w("中午","zhōngwǔ","siang hari; tengah hari","Kata Benda"),
    w("种","zhǒng","jenis; macam","Kata Penghitung"),
    w("重要","zhòngyào","penting","Kata Sifat"),
    w("周末","zhōumò","akhir pekan; weekend","Kata Benda"),
    w("住","zhù","tinggal; berdiam di","Kata Kerja"),
    w("祝贺","zhùhè","mengucapkan selamat","Kata Kerja"),
    w("注意","zhùyì","memperhatikan; berhati-hati","Kata Kerja"),
    w("准备","zhǔnbèi","mempersiapkan; bersiap","Kata Kerja"),
    w("准时","zhǔnshí","tepat waktu","Kata Sifat"),
    w("桌子","zhuōzi","meja","Kata Benda"),
    w("自己","zìjǐ","diri sendiri","Kata Ganti"),
    w("自行车","zìxíngchē","sepeda","Kata Benda"),
    w("走","zǒu","berjalan; pergi","Kata Kerja"),
    w("最","zuì","paling; ter-","Kata Keterangan"),
    w("最近","zuìjìn","belakangan ini; akhir-akhir ini","Kata Keterangan"),
    w("昨天","zuótiān","kemarin","Kata Benda"),
    w("左","zuǒ","kiri","Kata Benda"),
    w("坐","zuò","duduk; naik (kendaraan)","Kata Kerja"),
    w("做","zuò","melakukan; membuat","Kata Kerja"),
    w("作业","zuòyè","pekerjaan rumah; PR","Kata Benda"),
]

# Load existing YCT vocab and add YCT4
with open('/Users/cunhiung/junxiongmandarinstudio1/data/vocab_yct.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

existing['words']['YCT4'] = YCT4
existing['levels']['YCT4'] = {'count': len(YCT4), 'official_word_count': 600}
existing['word_count'] = sum(len(v) for v in existing['words'].values())

with open('/Users/cunhiung/junxiongmandarinstudio1/data/vocab_yct.json', 'w', encoding='utf-8') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"YCT4: {len(YCT4)} words written")
print(f"Total YCT: {existing['word_count']} words")
